// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JPClient is the client API for JP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JPClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type jPClient struct {
	cc grpc.ClientConnInterface
}

func NewJPClient(cc grpc.ClientConnInterface) JPClient {
	return &jPClient{cc}
}

func (c *jPClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/proto.JP/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JPServer is the server API for JP service.
// All implementations must embed UnimplementedJPServer
// for forward compatibility
type JPServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	mustEmbedUnimplementedJPServer()
}

// UnimplementedJPServer must be embedded to have forward compatible implementations.
type UnimplementedJPServer struct {
}

func (UnimplementedJPServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedJPServer) mustEmbedUnimplementedJPServer() {}

// UnsafeJPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JPServer will
// result in compilation errors.
type UnsafeJPServer interface {
	mustEmbedUnimplementedJPServer()
}

func RegisterJPServer(s grpc.ServiceRegistrar, srv JPServer) {
	s.RegisterService(&JP_ServiceDesc, srv)
}

func _JP_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JPServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.JP/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JPServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JP_ServiceDesc is the grpc.ServiceDesc for JP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.JP",
	HandlerType: (*JPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _JP_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jock.proto",
}
